server:
  port: 8080

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://host.docker.internal:3306/loan?characterEncoding=UTF-8&serverTimezone=Asia/Seoul
    username: root
    password: 1234
#    driverClassName: org.h2.Driver
#    url: jdbc:h2:mem:testdb
#    username: sa
#    password:
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
      naming:
        physical-strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
#    database-platform: org.hibernate.dialect.H2Dialect
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    database: mysql
#  h2:
#    console:
#      path: /h2-console
#      enabled: true
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
      location: /Users/epike/Documents/projects/uploadtest

logging.level:
  org.hibernate.SQL: debug
