apiVersion: apps/v1
kind: Deployment
metadata:
  name: jake-loan
spec:
  selector:
    matchLabels:
      app: jake-loan
  template:
    metadata:
      labels:
        app: jake-loan
    spec:
      containers:
        - name: jake-loan
          image: jake-loan
          ports:
            - containerPort: 8080